FROM alpine:3.22

RUN apk add --no-cache openssh-client \
    && addgroup -g 1000 tunnel \
    && adduser -D -u 1000 -G tunnel tunnel
COPY ssh-tunnel-entrypoint.sh /usr/local/bin/ssh-tunnel-entrypoint
RUN chmod 755 /usr/local/bin/ssh-tunnel-entrypoint

USER tunnel
ENTRYPOINT ["ssh-tunnel-entrypoint"]
